services:
     - type: web
       name: streamlit-app
       env: python
       buildCommand: pip install -r requirements.txt
       startCommand: streamlit run app.py
       envVars:
         - key: PYTHON_VERSION
           value: 3.9.0